### ISSUE TITLE
No record in mods

### ISSUE THREAD

**Issue by dimankiev** [Kaskouy/SFS-Closest-Approach-Line#1]
No record appears in old or new (beta) steam modloader versions
Placed in two paths for both old and new modloaders:
 - SFS/Mods
 - SFS/Data/MODS
 
 Expected result: 
  - I have record "Closest Approach Line" in MODS/Mods tab in the main menu
  - I have blue/green nav lines in game, while navigating to other space object
  
 Actual result:
  - Other mods: loaded, this mod: no signs of it

**Comment by Kaskouy** [comment]
The issue was due to the release of a new mod loader. The mod has been ported to the new version, it is now fully compatible.

_Note_:  The correct folder for it is now **SFS/Mods**, the other is the old one, it won't work anymore.
